ARG ENVOY_BUILD_IMAGE

FROM $ENVOY_BUILD_IMAGE as base

ARG BUILD_CMD

WORKDIR /envoy-sources

# RUN groupadd --gid $(id -g) -f envoygroup \
#   && useradd -o --uid $(id -u) --gid $(id -g) --no-create-home --home-dir /build envoybuild \
#   && usermod -a -G pcap envoybuild \
#   && mkdir /build /source \
#   && chown envoybuild:envoygroup /build /source

COPY . .

RUN bash -c "bazel/setup_clang.sh /opt/llvm"
RUN bash -c "$BUILD_CMD"


#sudo -EHs -u envoybuild bash -c
