#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

set +x

cat <<- EOM
Building Envoy for:
    PLATFORM: ${GOOS}
    ARCHITECTURE: ${GOARCH}
    DISTRO: ${DISTRO}
    ENVOY_TAG: ${ENVOY_TAG}
    ENVOY_VERSION_TRIMMED=${ENVOY_VERSION_TRIMMED}
    ENVOY_SOURCE_DIR: ${ENVOY_SOURCE_DIR}
    ENVOY_BUILD_TOOLS_DIR: ${ENVOY_BUILD_TOOLS_DIR}
    BUILD_ENVOY_FROM_SOURCES: ${BUILD_ENVOY_FROM_SOURCES}
    DOCKER_REGISTRY: ${DOCKER_REGISTRY}
EOM