name: CI_ARM
on: 
  workflow_dispatch:
    inputs:
      envoyTag:
        description: 'envoy tag to build'
        type: string
        required: true
      s3CachePrefix:
        description: 'envoy s3 cache prefix'
        type: string
        default: envoy
jobs:
  build:
    env:
      BAZEL_DEFAULT_EXTRA_OPTIONS: >-
        --discard_analysis_cache 
        --nostamp 
        --nouse_action_cache
        --io_nice_level=4
    strategy:
      fail-fast: false
      matrix:
        distro: [alpine, centos]
        arch: [amd64, arm64]
        # exclude:
        #   # CentOS image doesn't have bazel  / git instlled in path and is empty
        #   # Issue: https://github.com/envoyproxy/envoy-build-tools/pull/154 (Still occurs on v1.22.2)
        #   - distro: centos
        #     arch: arm64
        #   # How to perform virtualization between amd64 host aand arm64/aarch64 target?
        #   - distro: darwin
        #     arch: arm64  
          

        #mode: [fips, debug, stripped]
        #include / exlcude combinations

        allow_failure: [false]
    runs-on: ${{ matrix.distro != 'darwin' && 'ubuntu-latest' || 'macos-latest' }}
    continue-on-error: ${{ matrix.allow_failure }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    
    - run: |
        make envoy_container
      env:
        TARGETOS: linux 
        TARGETARCH: ${{matrix.arch}} 
        DISTRO: ${{matrix.distro}} 
        ENVOY_TAG: v1.22.0 
        BUILD_ENVOY_FROM_SOURCES: true
