name: ci_multi_platform
on: 
  workflow_dispatch:
    inputs:
      envoyTag:
        description: 'envoy tag to build'
        type: string
        default: v1.22.2
        required: false
      s3CachePrefix:
        description: 'envoy s3 cache prefix'
        type: string
        default: envoy
      noBuildxCache:
        description: 'Ignore docker buildx cache'
        type: boolean
        default: false

jobs:
  metadata:
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      ebToolsTag: "${{steps.eb_tools_metadata.outputs.ebToolsTag}}"
      ebSHA: "${{steps.eb_metadata.outputs.ebSHA}}"
      bazelCacheKey: "${{steps.eb_metadata.outputs.bazelCacheKey}}"
    steps:

      - uses: actions/checkout@v3

      - name: Set envoyproxy-build-tools metadata
        id: eb_tools_metadata
        run: |
          echo "::set-output name=ebToolsTag::$(curl --fail --location --silent https://raw.githubusercontent.com/envoyproxy/envoy/${{github.event.inputs.envoyTag}}/.bazelrc | grep envoyproxy/envoy-build-ubuntu | sed -e 's#.*envoyproxy/envoy-build-ubuntu:\(.*\)#\1#' | uniq)"
      
      - name: Set envoy-builds metadata
        id: eb_metadata
        run: |
          echo "::set-output name=ebSHA::$(git rev-parse --short HEAD)"
          echo "::set-output name=bazelCacheKey::${{github.event.inputs.envoyTag}}-${{hashFiles('tools/envoy/**/*.sh', 'tools/envoy/util/extensions.py', 'Dockerfile*')}}"
        
  # Always prefetch bazel only for alpine
  prefetch:
    needs: metadata
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        allow_failure: [true]
        os: [linux]
    continue-on-error: false
    steps:

    - name: Inspect
      run: |
        echo "Build Environment:"
        echo "envoyTag: ${{github.event.inputs.envoyTag}}"
        echo "envoyBuildToolsTag: ${{needs.metadata.outputs.ebToolsTag}}"
        echo "envoyBuildSHA: ${{needs.metadata.outputs.ebSHA}}"
        echo "bazelCacheKey: ${{needs.metadata.outputs.bazelCacheKey}}"

    - uses: actions/checkout@v3
    
    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    
    - name: Login to DockerHub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.GHA_DOCKERHUB_PUSH_USER }}
        password: ${{ secrets.GHA_KONG_DOCKERHUB_PUSH_TOKEN }}

    # Fallback cache key: ${{env.ebSHA}}-${{env.envoyTag}}
    - name: Build Envoy Deps and export cache
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        file: Dockerfile.${{matrix.os}}
        no-cache: ${{github.event.inputs.noBuildxCache}}
        build-args: |
          ENVOY_BUILD_TOOLS_VERSION=${{needs.metadata.outputs.ebToolsTag}}
          ENVOY_TAG=${{env.envoyTag}}
        target: envoy-deps
        cache-to: |
          type=registry,mode=max,ref=kong/envoy-builds-cache:envoy-deps-${{env.bazelCacheKey}}
        cache-from: |
          type=registry,ref=kong/envoy-builds-cache:envoy-deps-${{env.bazelCacheKey}}
        tags: |
          kong/envoy-builds:envoy-deps-${{env.bazelCacheKey}}
          kong/envoy-builds:envoy-deps-${{env.ebSHA}}-${{env.envoyTag}}
      env:
        envoyTag: ${{github.event.inputs.envoyTag}}
        ebSHA: ${{needs.metadata.outputs.ebSHA}}
        bazelCacheKey: ${{needs.metadata.outputs.bazelCacheKey}}

  build:
    needs: [metadata, prefetch]
    strategy:
      fail-fast: false
      matrix:
        allow_failure: [false]
        distro: [alpine, centos]
        os: [linux]
        arch: [amd64, arm64]
        bazel_compile_mode: [opt, dbg]
        bazel_compile_options: [""]
        include:
          - distro: alpine
            os: linux
            arch: amd64
            bazel_compile_mode: opt
            bazel_compile_options: "--define boringssl=fips"
          - distro: alpine
            os: linux
            arch: amd64
            bazel_compile_mode: dbg
            bazel_compile_options: "--define boringssl=fips"
        #mode: [fips, debug, stripped]
        #include / exlcude combinations
    runs-on: 'ubuntu-latest'
    continue-on-error: false
    steps:
    
    - name: Inspect
      run: |
        echo "Build Environment:"
        echo "envoyTag: ${{github.event.inputs.envoyTag}}"
        echo "envoyBuildToolsTag: ${{needs.metadata.outputs.ebToolsTag}}"
        echo "envoyBuildSHA: ${{needs.metadata.outputs.ebSHA}}"
        echo "bazelCacheKey: ${{needs.metadata.outputs.bazelCacheKey}}"

    - uses: actions/checkout@v3

    - name: Maximize build space
      run: |
        if [[ ${{ matrix.distro }} != 'darwin' ]]; then
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo docker system prune -f
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y 'php.*'
          sudo apt-get remove -y '^mongodb-.*'
          sudo apt-get remove -y '^mysql-.*'
          sudo apt-get remove -y azure-cli google-cloud-sdk google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo swapoff -a
          sudo rm -f /mnt/swapfile
          docker system prune -af
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    
    - name: Login to DockerHub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.GHA_DOCKERHUB_PUSH_USER }}
        password: ${{ secrets.GHA_KONG_DOCKERHUB_PUSH_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        no-cache: ${{github.event.inputs.noBuildxCache}}
        context: .
        file: Dockerfile.${{env.artifactOS}}
        build-args: |
          ENVOY_BUILD_TOOLS_VERSION=${{needs.metadata.outputs.ebToolsTag}}
          ENVOY_BUILD_TOOLS_IMAGE_BASE_VARIANT=${{env.ebToolsImgBaseVariant}}
          ENVOY_TAG=${{env.envoyTag}}
          DISTRO=${{env.distro}}
          BAZEL_BUILD_EXTRA_OPTIONS=${{env.bazelBuildExtraOptions}}
          BAZEL_COMPILATION_MODE=${{env.bazelCompilationMode}}
        platforms: ${{matrix.os}}/${{matrix.arch}}
        target: envoy-build
        cache-to: |
          type=registry,mode=max,ref=kong/envoy-builds-cache:envoy-builds-${{env.distro}}-${{env.bazelCompilationMode}}${{env.artifactExt}}-${{env.bazelCacheKey}}
        cache-from: |
          type=registry,ref=kong/envoy-builds-cache:envoy-deps-${{env.bazelCacheKey}}
          type=registry,ref=kong/envoy-builds-cache:envoy-builds-${{env.distro}}-${{env.bazelCompilationMode}}${{env.artifactExt}}-${{env.bazelCacheKey}}
        tags: ${{env.registry}}/${{env.repo}}:envoy-builds-${{env.ebSHA}}-${{env.envoyTag}}-${{env.distro}}-${{env.bazelCompilationMode}}${{env.artifactExt}}
      env:
        ebToolsImgBaseVariant: ${{matrix.distro == 'darwin' && 'alpine' || matrix.distro}} 
        registry: kong
        repo: envoy-builds
        envoyTag: ${{github.event.inputs.envoyTag}}
        distro: ${{matrix.distro}}
        ebSHA: ${{needs.metadata.outputs.ebSHA}}
        bazelCacheKey: ${{needs.metadata.outputs.bazelCacheKey}}
        artifactOS: ${{matrix.os}}
        artifactArch: ${{matrix.arch}}
        bazelBuildExtraOptions: >-
          --profile=/tmp/profile.gz
          --discard_analysis_cache
          --nostamp 
          --nouse_action_cache
          ${{matrix.bazel_compile_options}}
        bazelCompilationMode: ${{matrix.bazel_compile_mode}}
        artifactExt: ${{ matrix.bazel_compile_options != '' && '-extended' || '' }}

   
    # Parse os nad arch from platform
    - name: Zip artifact
      run: |
        IMAGE=${{env.registry}}/${{env.repo}}:envoy-builds-${{env.ebSHA}}-${{env.envoyTag}}-${{env.distro}}-${{env.bazelCompilationMode}}${{env.artifactExt}}
        docker pull ${IMAGE}
        docker inspect ${IMAGE} 
        mkdir -p ${{env.out_dir}}
        id=$(docker create ${IMAGE})
        docker cp $id:/app/envoy/bazel-bin/contrib/exe/envoy-static ${{env.out_dir}}/${{env.out_bin}}
        if [[ -f ${{env.out_dir}}/${{env.out_bin}} ]]; then  
          tar -C ${{env.out_dir}} -czvf envoy-${{env.envoyTag}}-${{env.distro}}-${{env.artifactOS}}-${{env.artifactArch}}-${{env.bazelCompilationMode}}${{env.artifactExt}}.tar.gz .
        fi
      env:
        registry: kong
        repo: envoy-builds
        envoyTag: ${{github.event.inputs.envoyTag}}
        distro: ${{matrix.distro}}
        ebSHA: ${{needs.metadata.outputs.ebSHA}} 
        artifactOS: ${{matrix.os}}
        artifactArch: ${{matrix.arch}}
        artifactExt: ${{ matrix.bazel_compile_options != '' && '-extended' || '' }}
        out_dir: build/artifacts
        out_bin: envoy-${{matrix.distro}}
        bazelCompilationMode: ${{matrix.bazel_compile_mode}}

    - name: Save artifact
      uses: actions/upload-artifact@v3
      id: save_artifacts
      with:
        name: artifacts
        path: |
          envoy-*.tar.gz
