name: test
on: 
  workflow_dispatch:
    inputs:
      envoyTag:
        description: 'envoy tag to build'
        type: string
        default: v1.22.2
        required: false
      s3CachePrefix:
        description: 'envoy s3 cache prefix'
        type: string
        default: envoy
      noBuildxCache:
        description: 'Ignore docker buildx cache'
        type: boolean
        default: false

jobs:
  build:
    if: always()
    env:
      ENVOY_DEPS_TAR: /tmp/envoy-deps.tar
    strategy:
      fail-fast: false
      matrix:
        allow_failure: [false]
        #distro: [alpine, centos]
        platforms: [linux/amd64, linux/arm64, darwin/amd64]
        #mode: [fips, debug, stripped]
        #include / exlcude combinations
    runs-on: 'ubuntu-latest'
    continue-on-error: ${{ matrix.allow_failure }}
    steps:
    
    - uses: jungwinter/split@v2
      id: split
      with:
        msg: '${{matrix.platforms}}'
        separator: '/'

    - name: Inspect
      run: |
        echo "Build Environment:"
        echo "envoyTag: ${{github.event.inputs.envoyTag}}"
        echo "envoyBuildToolsTag: ${{needs.metadata.outputs.ebToolsTag}}"
        echo "OS: ${{env.artifactOS}}"
        echo "ARCH: ${{env.artifactArch}}"
      env:
        artifactOS: ${{ steps.split.outputs._1 }}
        artifactArch: ${{ steps.split.outputs._2 }}
        
    - uses: actions/checkout@v3

    
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2
    
    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: false
        load: true
        no-cache: ${{github.event.inputs.noBuildxCache}}
        context: .
        file: Dockerfile.test
        build-args: |
          ENVOY_TAG=${{env.envoyTag}}
        platforms: ${{matrix.platforms}}
        target: deps
        tags: ${{env.registry}}/${{env.repo}}:${{env.envoyTag}}
      env: 
        registry: kong
        repo: envoy-builds
        envoyTag: ${{github.event.inputs.envoyTag}}

    - name: Inspect Image
      run: |
        IMAGE=${{env.registry}}/${{env.repo}}:${{env.envoyTag}} \
        make inspect_envoy_image
      env:
        registry: kong
        repo: envoy-builds
        envoyTag: ${{github.event.inputs.envoyTag}}