name: test
on: 
  workflow_dispatch:
    inputs:
      envoyTag:
        description: 'envoy tag to build'
        type: string
        default: v1.22.2
        required: false
      s3CachePrefix:
        description: 'envoy s3 cache prefix'
        type: string
        default: envoy
      noBuildxCache:
        description: 'Ignore docker buildx cache'
        type: boolean
        default: false

jobs:
  build:
    if: always()
    env:
      ENVOY_DEPS_TAR: /tmp/envoy-deps.tar
    strategy:
      fail-fast: false
      matrix:
        allow_failure: [false]
        distro: [alpine, centos, windows]
        platforms: [linux/amd64, linux/arm64, windows/amd64, windows/arm64]
        #mode: [fips, debug, stripped]
        #include / exlcude combinations
    runs-on: ${{ matrix.distro != 'windows' && 'ubuntu-latest' || windows-2019' }}
    continue-on-error: ${{ matrix.allow_failure }}
    steps:
    
    - uses: jungwinter/split@v2
      id: split
      with:
        msg: '${{matrix.platforms}}'
        separator: '/'

    - name: Inspect
      run: |
        echo "Build Environment:"
        echo "envoyTag: ${{github.event.inputs.envoyTag}}"
        echo "envoyBuildToolsTag: ${{needs.metadata.outputs.ebToolsTag}}"
        echo "OS: ${{env.artifactOS}}"
        echo "ARCH: ${{env.artifactArch}}"
      env:
        artifactOS: ${{ steps.split.outputs._0 }}
        artifactArch: ${{ steps.split.outputs._1 }}
        
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - uses: docker/setup-buildx-action@v2
      id: buildx
      with:
        install: true
